version: "3"
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    restart: on-failure
    ports:
      - "9090:9090"
    networks:
      - fgsnetwork
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-storage:/etc/prometheus
  
  node-exporter:
    image: prom/node-exporter:latest
    restart: on-failure
    ports:
      - "9100:9100"
    networks:
      - fgsnetwork

  grafana:
    image: grafana/grafana:7.4.0
    restart: on-failure
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
      - ./grafana/dashboards/jsons:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - fgsnetwork

  app:
    build: ../../
    restart: on-failure
    ports:
      - "5000:5000"
    networks:
      - fgsnetwork
  
networks:
  fgsnetwork:

volumes:
  grafana-storage:
  prometheus-storage: