{
 "title": "Four Golden Signals",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latência",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{controller=\"Latency\",method=\"GET\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{controller=\"Latency\",method=\"GET\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{controller=\"Latency\",method=\"GET\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Requisições / s (Tráfego)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{controller=\"Latency\",method=\"GET\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memória dotnet (Saturação)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "dotnet_total_memory_bytes" }
   ]
  },
  {
   "title": "Erros 500",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{controller=\"Latency\",method=\"GET\",code=~\"5..\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memória dotnet (Saturação)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  }
 ]
}