global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090

  - job_name: fgs
    honor_timestamps: true
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: 
          - app:5000

  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
      - targets:
          - node-exporter:9100

 